filein1 = open("poem1.txt","r",encoding = 'UTF-8')
filein2 = open("poem2.txt","r",encoding = 'UTF-8')
line1 = filein1.readlines()
line2 = filein2.readlines()
s1 = set(line1)
s2 = set(line2)
s_inter = s1.intersection(s2)
s_dif1 = s1.difference(s2)
s_dif2 = s2.difference(s1)
print("在两个文件中有{}行相同。".format(len(s_inter)))
print("有{}行存在于poem1.txt中而不存在于poem2.txt中，有{}行存在于poem2.txt中而不存在于poem1.txt中。".format(len(s_dif1),len(s_dif2)))